#!/bin/sh

udevd &
udevadm trigger

fbcp &

RUN apt-get update && apt-get install -y uuid-runtime

serial=`cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2`
if [ ! -e "afUuid.txt" ]; then
   uuidgen > afUuid.txt
fi
deviceId=`cat afUuid.txt`;

export WPE_URL="$BASE_URL?deviceId=$deviceId&serial=$serial&type=pi"

WPE_BCMRPI_TOUCH=1 WPELauncher $WPE_URL
